### ISSUE TITLE
M.2 2280 support

### ISSUE THREAD

**Issue by uqtsherr** [berin-aquaquad/orange-pi-5#1]
Given the case is oversized, consider support typical 2280 SSDs.

I have a really basic Creo rest which bolts to the 2230 and 2242 mount points and provides a mount hole for a 2280 at the optimum bolt height. It could either be included or incorporated into the PCB mounting solution.

**Comment by berin-aquaquad** [comment]
I dont have one of those on hand. I'll look into it. The pcb I'm talking about is just for the headphone jack and power button and RTC battery. tiny DIY level stuff. My case is 135mm long along the base. The 2280 ssd is 22x80mm That could fit in the bottom easy. The top at the shortest is 104mm long. Vertical its 100mm tall. As is the 2280 would fit anywhere. IMO a remote header would be the best choice. I just posted a basic side view of current version dimensions.
