### ISSUE TITLE
SBC file?

### ISSUE THREAD

**Issue by asid61** [berin-aquaquad/orange-pi-5#2]
I can see all the case files but there doesn't seem to be a file with just the SBC anywhere?

**Comment by berin-aquaquad** [comment]
Just dbl checked everything is there. What "file"/"file format" are you looking for? Under the folder "/cad drawing/" there is a file a file called  " opi5 micro desktop.rsdoc" using Designspark Cad software (ITS 100% FREE AND AS POWERFUL AS FUSION 360) You can look at the entire drawing. All broken out files come from that master file. Using Designspark dbl click on the SBC using the arrow/select icon. then right mouse and HIDE OTHERS. You will be left with just the OPI5 SBC. Everything is still listed in the tree to the left. If you want to Un-hide anything.

**Comment by berin-aquaquad** [comment]
What is your plan with the SBC cad drawing its self. also assume its 98% accurate I only find errors as I'm building the hardware its self. Thousands of people have downloaded my design but I've see almost no responce.

**Comment by asid61** [comment]
I was planning on using the SBC cad to make my own casing actually, but I couldn't find it so I ended up looking elsewhere. The assembly didn't load quite right for me because I had to convert it to another format.

**Comment by berin-aquaquad** [comment]
Designspark is a great cad software. The main cad file has everything in it assembled. And everything is in the build tree. There are no missing parts. OPI5MICRO DESKTOP.RSDOC Is the main file.  Again try downloading and using the free cad software designspark. It is as powerful as fusion360. The pay for version is called Spaceclaim.

**Comment by samuk** [comment]
Could you output this file as a .stl please?

**Comment by samuk** [comment]
Or maybe a .DXF https://grabcad.com/questions/can-anyone-change-a-rsdoc-file-to-a-stp-or-igs-file 

I don't have windows so can't install DesignSpark
